[package]
name = "card_less_reader"
version = "0.1.0"
authors = ["Ð˜ <nigma143@mail.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = ""
thiserror = ""
